# Copyright 2026 Anthropic PBC
# SPDX-License-Identifier: Apache-2.0
"""Self-contained legacy tool implementations for the CMA sandbox.

This file is uploaded into the Managed Agent's sandbox as tools.py so the
starter agent can call the original 12 tools via Bash:

    python -c 'import sys; sys.path.insert(0,"/mnt/session/uploads"); \
               import tools; print(tools.list_low_stock())'

It has NO third-party imports — only stdlib — so it runs in a bare sandbox.

Subagent calls are stubbed with sleep+canned-prose to demonstrate the
latency/lossy-handoff pattern without requiring API access in the sandbox.
The original 2025 implementation made a real anthropic.messages.create() call
per subagent (~4s, ~800 tokens each); the stub reproduces the latency and
the prose-not-JSON return shape that the workshop's F2/F3 lessons depend on.

Security note: the data these tools read is fully synthetic, generated by
data/seed.py with hardcoded supplier/product names — there is no external
content path. In a real deployment where supplier catalogs or invoice lines
come from third parties, these tools would be a prompt-injection vector
(untrusted CSV text → agent context → bash with write access). Mitigation
patterns: (a) sanitize free-text fields before use, (b) gate writes behind
human approval, (c) run ingestion through a read-only subagent that returns
only structured data. We do (a) below as a teaching example via _safe().
"""
from __future__ import annotations
import csv
import io
import json
import re
import time
from datetime import datetime, timezone
from pathlib import Path

DATA = Path("/mnt/user/data")
_SAFE_RE = re.compile(r"[^\w\s.,:/$%+()\-]")


def _safe(s: object) -> str:
    """Strip characters outside a conservative allowlist before interpolating
    free-text CSV fields into subagent prompts."""
    return _SAFE_RE.sub("", str(s))[:500]


def _read_csv(name: str) -> list[dict]:
    with open(DATA / name, newline="") as f:
        return list(csv.DictReader(f))


def _sink_dir() -> Path:
    # Canonical sink path across prompts, skills, and the eval harness's sync step.
    d = Path("/mnt/user/sinks")
    d.mkdir(parents=True, exist_ok=True)
    return d


def _append_jsonl(name: str, record: dict) -> None:
    record = {"ts": datetime.now(timezone.utc).isoformat(timespec="seconds"), **record}
    with open(_sink_dir() / name, "a") as f:
        f.write(json.dumps(record) + "\n")


def _latest_stock() -> list[dict]:
    rows = _read_csv("stock_levels.csv")
    latest = max(r["date"] for r in rows)
    return [r for r in rows if r["date"] == latest]


def _simulate_subagent_latency() -> None:
    """Stand-in for the original anthropic.messages.create() round-trip."""
    time.sleep(4)


# ─── the 12 tools ──────────────────────────────────────────────────────────

def get_stock_level(sku: str, warehouse: str) -> str:
    for r in _latest_stock():
        if r["sku"] == sku and r["warehouse"] == warehouse:
            return json.dumps({"sku": sku, "warehouse": warehouse,
                               "on_hand": int(r["on_hand"]), "as_of": r["date"]})
    return json.dumps({"error": f"no record for {sku} at {warehouse}"})


def list_low_stock() -> str:
    reorder = {p["sku"]: int(p["reorder_point"]) for p in _read_csv("products.csv")}
    out = io.StringIO()
    w = csv.writer(out)
    w.writerow(["sku", "warehouse", "on_hand", "reorder_point", "as_of"])
    for r in _latest_stock():
        rp = reorder.get(r["sku"], 0)
        if int(r["on_hand"]) < rp:
            w.writerow([r["sku"], r["warehouse"], r["on_hand"], rp, r["date"]])
    return out.getvalue()


def get_sales_velocity(sku: str, days: int = 14) -> str:
    rows = sorted((r for r in _read_csv("sales_history.csv") if r["sku"] == sku),
                  key=lambda r: r["date"])[-days:]
    total = sum(int(r["units_sold"]) for r in rows)
    return json.dumps({"sku": sku, "window_days": days, "total_units": total,
                       "daily_avg": round(total / max(days, 1), 2)})


def forecast_demand(sku: str, note: str = "") -> str:
    rows = sorted((r for r in _read_csv("sales_history.csv") if r["sku"] == sku),
                  key=lambda r: r["date"])
    units = [int(r["units_sold"]) for r in rows]
    mean = (sum(units) / len(units)) if units else 0.0
    prod = next((p for p in _read_csv("products.csv") if p["sku"] == sku), {})
    flags = []
    if prod.get("is_seasonal") == "1":
        flags.append("seasonal item")
    if prod.get("promo_next_month") == "1":
        flags.append("promo scheduled next month")
    _simulate_subagent_latency()
    flag_txt = " and ".join(flags) if flags else "no special flags"
    return (
        f"Based on the 90-day history, I'd estimate ~{int(mean * 30)} units for "
        f"the next 30 days. Confidence is moderate-low given {flag_txt}. "
        f"Method: trailing mean ({mean:.1f}/day). The estimate could shift "
        f"materially if the {flag_txt or 'demand pattern'} plays out differently."
    )


def get_supplier_catalog(sku: str) -> str:
    suppliers = {s["supplier_id"]: s for s in _read_csv("suppliers.csv")}
    out = []
    for row in _read_csv("supplier_catalog.csv"):
        if row["sku"] != sku:
            continue
        sup = suppliers.get(row["supplier_id"], {})
        out.append({
            "supplier_id": row["supplier_id"], "name": sup.get("name", ""),
            "unit_price": float(row["unit_price"]),
            "min_order_qty": int(row["min_order_qty"]),
            "lead_time_days": int(sup.get("lead_time_days", 0)),
            "reliability": float(sup.get("reliability", 0)),
        })
    return json.dumps(out)


def compare_supplier_quotes(sku: str) -> str:
    quotes = json.loads(get_supplier_catalog(sku))
    _simulate_subagent_latency()
    if not quotes:
        return f"No suppliers on file for {_safe(sku)}."
    best = min(quotes, key=lambda q: q["unit_price"])
    return (
        f"Of the {len(quotes)} options, {_safe(best['supplier_id'])} "
        f"({_safe(best.get('name',''))}) looks strongest at "
        f"${best['unit_price']:.2f}/unit with a {best['lead_time_days']}-day lead "
        f"and {best['reliability']:.2f} reliability. The others are pricier or "
        f"slower. Recommendation: order from {_safe(best['supplier_id'])}."
    )


def create_purchase_order(sku: str, supplier_id: str, qty: int) -> str:
    rec = {"sku": sku, "supplier_id": supplier_id, "qty": int(qty)}
    _append_jsonl("purchase_orders.jsonl", rec)
    return json.dumps({"status": "created", **rec})


def update_erp_record(sku: str, field: str, value: str) -> str:
    rec = {"sku": sku, "field": field, "value": value}
    _append_jsonl("erp_writes.jsonl", rec)
    return json.dumps({"status": "ok", **rec})


def send_slack_alert(sku: str, summary: str) -> str:
    _simulate_subagent_latency()
    text = (
        f":warning: *{_safe(sku)}* — {_safe(summary)}. "
        f"Flagging for ops review; please confirm next steps."
    )
    _append_jsonl("outbox.jsonl", {"channel": "#ops-inventory", "sku": sku, "message": text})
    return json.dumps({"status": "sent", "channel": "#ops-inventory", "preview": text[:120]})


def draft_email_to_supplier(supplier_id: str, sku: str, qty: int) -> str:
    _simulate_subagent_latency()
    text = (
        f"Hello,\n\nWe'd like to place an order for {int(qty)} units of {_safe(sku)}. "
        f"Please confirm availability and your earliest delivery window.\n\n"
        f"Thanks,\nStockPilot Ops"
    )
    _append_jsonl("outbox.jsonl", {"channel": f"email:{supplier_id}", "message": text})
    return json.dumps({"status": "drafted", "to": supplier_id, "preview": text[:120]})


def generate_weekly_report(warehouse: str) -> str:
    low = [r for r in _latest_stock() if r["warehouse"] == warehouse]
    reorder = {p["sku"]: int(p["reorder_point"]) for p in _read_csv("products.csv")}
    below = [r for r in low if int(r["on_hand"]) < reorder.get(r["sku"], 0)]
    lines = [
        f"Weekly Inventory Report — {warehouse}",
        f"As of {low[0]['date'] if low else 'n/a'}",
        f"SKUs tracked: {len(low)}",
        f"Below reorder point: {len(below)}",
        "",
        "Top concerns:",
    ]
    for r in sorted(below, key=lambda r: int(r["on_hand"]))[:10]:
        lines.append(f"  - {r['sku']}: {r['on_hand']} on hand (reorder at {reorder[r['sku']]})")
    return "\n".join(lines)


def search_web_for_disruptions(query: str) -> str:
    return (
        "Recent supply-chain headlines (cached 2026-04-26):\n"
        "- Port of Long Beach reports 3-day berth delays amid labor talks\n"
        "- Trans-Pacific spot rates up 6% week-over-week\n"
        "- Semiconductor lead times stabilizing after Q1 shortages\n"
        "- No major weather disruptions forecast for North American corridors\n"
    )


TOOL_NAMES = [
    "get_stock_level", "list_low_stock", "get_sales_velocity", "forecast_demand",
    "get_supplier_catalog", "compare_supplier_quotes", "create_purchase_order",
    "update_erp_record", "send_slack_alert", "draft_email_to_supplier",
    "generate_weekly_report", "search_web_for_disruptions",
]
